 Resources:
  BabayTest:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Babay
      AttributeDefinitions:
        - AttributeName: Name
          AttributeType: S
      KeySchema:
        - AttributeName: Name
        - KeyType: HASH
