Resources:
  BabayTestTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Babay
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST


